### ISSUE TITLE
Installing simplelzo1x on Win32 Environment

### ISSUE THREAD

**Issue by rawmain** [c3c/E-Safenet#1]
Hello

I'm having some issues trying to install simplelzo1x on Win32 environment with the following configuration :
- Python v2.7.12
- MinGW32 GCC v4.9.3-1 
- LZO 32bit v1.11

I keep on getting these error messages (ignored warnings) when executing from an Administrative Command Prompt :

```
C:\XPMODEFILES\Stonex\One_ROM_0\E-Safenet-master\simplelzo1x>python setup.py install
running install
running build
running build_ext
building 'simplelzo1x' extension
C:\MinGW\bin\gcc.exe -mdll -O -Wall -Iliblzo -IC:\Python27\include -IC:\Python27\PC -c simplelzo1xmodule.c -o build\temp.win32-2.7\Release\simplelzo1xmodule.o
simplelzo1xmodule.c: In function 'compress':
simplelzo1xmodule.c:103:5: warning: "/*" within comment [-Wcomment]
     /* return */
 ^
simplelzo1xmodule.c: In function 'decompress':
simplelzo1xmodule.c:119:9: warning: variable 'err' set but not used [-Wunused-but-set-variable]
     int err;
         ^
writing build\temp.win32-2.7\Release\simplelzo1x.def
C:\MinGW\bin\gcc.exe -shared -s build\temp.win32-2.7\Release\simplelzo1xmodule.o build\temp.win32-2.7\Release\simplelzo1x.def -Lliblzo/32bit -LC:\Python27\libs -LC:\Python27\PCbuild -LC:\Python27\PC\VS9.0 -llzo -lpython27 -lmsvcr90 -o build\lib.win32-2.7\simplelzo1x.pyd
build\temp.win32-2.7\Release\simplelzo1xmodule.o:simplelzo1xmodule.c:(.text+0x80): undefined reference to `lzo1x_decompress'
build\temp.win32-2.7\Release\simplelzo1xmodule.o:simplelzo1xmodule.c:(.text+0x181): undefined reference to `lzo1x_1_compress'
build\temp.win32-2.7\Release\simplelzo1xmodule.o:simplelzo1xmodule.c:(.text+0x24d): undefined reference to `__lzo_init'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1
```

Thanks in advance for your help.

**Comment by c3c** [comment]
Hey rawmain,

I think the problem here is that you're trying to link an ELF file compiled for Linux (the liblzo.a) on a Win32 system. The code was produced as a proof-of-concept and is not very portable.

In case you want to use this module on Windows, you'll need to compile the LZO static library on Windows and place that in the 32bit/64bit directory. Here's a [link](https://files.scene.org/view/mirrors/hornet/code/compress/lzo100.zip) to LZO 1.00 (which is the exact version we encountered in E-Safenet encrypted files). 

Hope that works.
Cedric

**Comment by c3c** [comment]
Link to LZO 1.00 included in README now. Closing this issue. Let me know if you require any more information.
